services:
  licensingservice:
    image: licensing-service
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILE_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge